[build]
  # Directory to change to before starting a build.
  # This is where we will look for package.json/.nvmrc/etc.
  # If not set, defaults to the root directory.
  base = 'docs/'
  publish = 'docs/.vuepress/dist'
  command = 'npm run docs:build'